<?php
class hrEmployeesSeeder extends Seeder {
    public function run()
    {
        DB::table('hr_employees')->truncate();
        DB::table('hr_employees')->insert(array(
            array(
//                'employee_id'             => '2',
                'true_id'                 => '1',
                'co_id'                   => '1',
                'name'                    => 'ahmed',
                'branch_id'               => '1',
                'employee_date'           =>  new DateTime(),
                'work_nature'             => 'دائم',
                'department_id'           => '3',
                'job_id'                  => '2',
                'salary'                  => '800.00',
                'ins_salary'              => '1000.15',
                'ins_val'                 => '12.20',
                'ins_no'                  => '21',
                'card_no'                 => '29405021400142',
                'cancel_date'             => date('Y-m-d', strtotime("+24 months")),
                'cancel_cause'            => 'because the time to finish tasks is to late',
                'sex'                     => 'ذكر',
                'marital'                 => 'متزوج',
                'religion'                => 'مسلم',
                'military_service'        => 'معافاة',
                'tel'                     => '0111112354',
                'address'                 => '2st masr el gedida',
                'birth_date'              => date('Y-m-d', strtotime("-25 year")),
                'certificate'             => 'Bachelor',
                'cert_date'               => date('Y-m-d', strtotime("-24 months")),
                'cert_location'           =>'ain shams',
                'remark'                  => 'this is el rased project ',
                'user_id'                 => '1',
                'pic'                     =>'',
                'finger_id'               => '12',
                'd_hours'                  =>'7',
                'comm1'                   => '11',
                'comm2'                   =>'22'
            ),
            array(
                'true_id'                 => '2',

//                'employee_id'             => '5',
                'co_id'                   => '1',
                'name'                    => 'moaaz',
                'branch_id'               => '1',
                'employee_date'           => new DateTime(),
                'work_nature'             => 'دائم',
                'department_id'           => '4',
                'job_id'                  => '5',
                'salary'                  => '1000.00',
                'ins_salary'              => '100.15',
                'ins_val'                 => '120',
                'ins_no'                  => '20',
                'card_no'                 => '29405021400500',
                'cancel_date'             => date('Y-m-d', strtotime("+24 months")),
                'cancel_cause'            => 'because the time to finish tasks is to late',
                'sex'                     => 'ذكر',
                'marital'                 => 'متزوج',
                'religion'                => 'مسلم',
                'military_service'        => 'معافاة',
                'tel'                     => '0111126659',
                'address'                 => '2st masr el gedida',
                'birth_date'              => date('Y-m-d', strtotime("-30 year")),
                'certificate'             => 'Bachelor',
                'cert_date'               => '',
                'cert_location'           =>'cairo university',
                'remark'                  => 'this is el rased project ',
                'user_id'                 => '2',
                'pic'                     =>'',
                'finger_id'               => '12',
                'd_hours'                  => '8',
                'comm1'                   => '21',
                'comm2'                   =>'15'
            ),
            array(
                'true_id'                 => '3',

//                'employee_id'             => '8',
                'co_id'                   => '1',
                'name'                    => 'omar',
                'branch_id'               => '2',
                'employee_date'           => new DateTime(),
                'work_nature'             => 'مؤقت',
                'department_id'           => '5',
                'job_id'                  => '4',
                'salary'                  => '1500',
                'ins_salary'              => '300.15',
                'ins_val'                 => '155.20',
                'ins_no'                  => '28',
                'card_no'                 => '29405021400201',
                'cancel_date'             => date('Y-m-d', strtotime("+36 months")),
                'cancel_cause'            => 'because the time to finish tasks is to late',
                'sex'                     => 'ذكر',
                'marital'                 => 'اعزب',
                'religion'                => 'مسلم',
                'military_service'        => 'معافاة',
                'tel'                     => '0111113354',
                'address'                 => '2st masr el gedida',
                'birth_date'              => date('Y-m-d', strtotime("-25 year")),
                'certificate'             => 'Bachelor',
                'cert_date'               => date('Y-m-d', strtotime("-2 year")),
                'cert_location'           =>'ain shams',
                'remark'                  => 'this is el rased project this is el rased project this is el rased project ',
                'user_id'                 => '3',
                'pic'                     =>'',
                'finger_id'               => '19',
                'd_hours'                 => '9',
                'comm1'                   => '77',
                'comm2'                   =>'23'
            ),
             array(
                 'true_id'                 => '4',
//                'employee_id'             => '1',
                 'co_id'                   => '1',
                'name'                    => 'hafez',
                'branch_id'               => '3',
                'employee_date'           => new DateTime(),
                'work_nature'             => 'دائم',
                'department_id'           => '5',
                'job_id'                  => '1',
                'salary'                  => '5000',
                'ins_salary'              => '1000',
                'ins_val'                 => '12.20',
                'ins_no'                  => '21',
                'card_no'                 => '29405021400188',
                'cancel_date'             => date('Y-m-d', strtotime("+24 months")),
                'cancel_cause'            => 'because the time to finish tasks is to late',
                'sex'                     => 'ذكر',
                'marital'                 => 'متزوج',
                'religion'                => 'مسلم',
                'military_service'        => 'معافاة',
                'tel'                     => '0111112354',
                'address'                 => '2st masr el gedida',
                'birth_date'              => date('Y-m-d', strtotime("-20 year")),
                'certificate'             => 'Bachelor',
                'cert_date'               => date('Y-m-d', strtotime("-2 year")),
                'cert_location'           =>'ain shams',
                'remark'                  => 'this is el rased project this is el rased project this is el rased project ',
                'user_id'                 => '4',
                'pic'                     =>'',
                'finger_id'               => '12',
                'd_hours'                  =>'7',
                'comm1'                   => '11',
                'comm2'                   =>'22'
            ),
             array(
                 'true_id'                 => '5',

//                'employee_id'             => '2',
                 'co_id'                   => '1',
                'name'                    => 'kareem',
                'branch_id'               => '2',
                'employee_date'           => new DateTime(),
                'work_nature'             => 'دائم',
                'department_id'           => '2',
                'job_id'                  => '3',
                'salary'                  => '1500',
                'ins_salary'              => '100',
                'ins_val'                 => '130',
                'ins_no'                  => '21',
                'card_no'                 => '29405021400145',
                'cancel_date'             => date('Y-m-d', strtotime("+12 months")),
                'cancel_cause'            => 'because the time to finish tasks is to late',
                'sex'                     => 'ذكر',
                'marital'                 => 'متزوج',
                'religion'                => 'مسلم',
                'military_service'        => 'معافاة',
                'tel'                     => '0111125214',
                'address'                 => '2st masr el gedida',
                'birth_date'              => date('Y-m-d', strtotime("-27 year")),
                'certificate'             => 'Bachelor',
                'cert_date'               => date('Y-m-d', strtotime("-2 year")),
                'cert_location'           =>'ain shams',
                'remark'                  => 'this is el rased project this is el rased project this is el rased project ',
                'user_id'                 => '5',
                'pic'                     =>'',
                'finger_id'               => '12',
                'd_hours'                  =>'7',
                'comm1'                   => '11',
                'comm2'                   =>'22'
            ),


        ));

    }
}