<?php
class hrEmployeesSeeder extends Seeder {
    public function run()
    {
        DB::table('hr_employees')->truncate();
        DB::table('hr_employees')->insert(array(
            array(
                'employee_id'             => '2',
                'co_id'                   => '1',
                'name'                    => 'ahmed',
                'branch_id'               => '123456789987456123',
                'employee_date'           => '',
                'work_nature'             => 'دائم',
                'department_id'           => '12',
                'job_id'                  => '3',
                'salary'                  => '5000.20',
                'ins_salary'              => '1000.15',
                'ins_val'                 => '12.20',
                'ins_no'                  => '21',
                'card_no'                 => '213512',
                'cancel_date'             => '',
                'cancel_cause'            => 'because the time to finish tasks is to late because the time to finish tasks is to late',
                'sex'                     => 'male',
                'marital'                 => 'متزوج',
                'religion'                => 'مسلم',
                'military_service'        => 'معافى ',
                'tel'                     => '111112354',
                'address'                 => '2st masr el gedida',
                'birth_date'              => '',
                'certificate'             => 'Bachelor',
                'cert_date'               => '',
                'cert_location'           =>'ain shams',
                'remark'                  => 'this is el rased project this is el rased project this is el rased project ',
                'user_id'                 => '123',
                'pic'                     =>'',
                'finger_id'               => '12',
                'd_hours'                  =>'7',
                'comm1'                   => '11',
                'comm2'                   =>'22'
            ),
            array(
                'employee_id'             => '5',
                'co_id'                   => '1',
                'name'                    => 'moaaz',
                'branch_id'               => '123',
                'employee_date'           => '',
                'work_nature'             => 'دائم',
                'department_id'           => '12',
                'job_id'                  => '5',
                'salary'                  => '600.20',
                'ins_salary'              => '100.15',
                'ins_val'                 => '120',
                'ins_no'                  => '20',
                'card_no'                 => '212',
                'cancel_date'             => '',
                'cancel_cause'            => 'because the time to finish tasks is to late because the time to finish tasks is to late',
                'sex'                     => 'male',
                'marital'                 => 'متزوج',
                'religion'                => 'مسلم',
                'military_service'        => 'تم الخدمه',
                'tel'                     => '111112111',
                'address'                 => '2st masr el gedida',
                'birth_date'              => '',
                'certificate'             => 'Bachelor',
                'cert_date'               => '',
                'cert_location'           =>'cairo university',
                'remark'                  => 'this is el rased project ',
                'user_id'                 => '189',
                'pic'                     =>'',
                'finger_id'               => '12',
                'd_hours'                  => '8',
                'comm1'                   => '21',
                'comm2'                   =>'15'
            ),
            array(
                'employee_id'             => '8',
                'co_id'                   => '1',
                'name'                    => 'omar',
                'branch_id'               => '456123',
                'employee_date'           => '',
                'work_nature'             => 'مؤقت',
                'department_id'           => '13',
                'job_id'                  => '7',
                'salary'                  => '2000',
                'ins_salary'              => '300.15',
                'ins_val'                 => '155.20',
                'ins_no'                  => '28',
                'card_no'                 => '2',
                'cancel_date'             => '',
                'cancel_cause'            => 'because the time to finish tasks is to late because the time to finish tasks is to late',
                'sex'                     => 'male',
                'marital'                 => 'اعزب',
                'religion'                => 'مسلم',
                'military_service'        => 'معافى ',
                'tel'                     => '111113354',
                'address'                 => '2st masr el gedida',
                'birth_date'              => '',
                'certificate'             => 'Bachelor',
                'cert_date'               => '',
                'cert_location'           =>'ain shams',
                'remark'                  => 'this is el rased project this is el rased project this is el rased project ',
                'user_id'                 => '122',
                'pic'                     =>'',
                'finger_id'               => '19',
                'd_hours'                  => '9',
                'comm1'                   => '77',
                'comm2'                   =>'23'
            ),
             array(
                'employee_id'             => '1',
                 'co_id'                   => '1',
                'name'                    => 'hafez',
                'branch_id'               => '23',
                'employee_date'           => '',
                'work_nature'             => 'دائم',
                'department_id'           => '11',
                'job_id'                  => '1',
                'salary'                  => '5000',
                'ins_salary'              => '1000',
                'ins_val'                 => '12.20',
                'ins_no'                  => '21',
                'card_no'                 => '213512',
                'cancel_date'             => '',
                'cancel_cause'            => 'because the time to finish tasks is to late because the time to finish tasks is to late',
                'sex'                     => 'male',
                'marital'                 => 'متزوج',
                'religion'                => 'مسلم',
                'military_service'        => 'معافى ',
                'tel'                     => '111112354',
                'address'                 => '2st masr el gedida',
                'birth_date'              => '',
                'certificate'             => 'Bachelor',
                'cert_date'               => '',
                'cert_location'           =>'ain shams',
                'remark'                  => 'this is el rased project this is el rased project this is el rased project ',
                'user_id'                 => '123',
                'pic'                     =>'',
                'finger_id'               => '12',
                'd_hours'                  =>'7',
                'comm1'                   => '11',
                'comm2'                   =>'22'
            ),
             array(
                'employee_id'             => '2',
                 'co_id'                   => '1',
                'name'                    => 'kareem',
                'branch_id'               => '123',
                'employee_date'           => '',
                'work_nature'             => 'دائم',
                'department_id'           => '12',
                'job_id'                  => '3',
                'salary'                  => '1500',
                'ins_salary'              => '100',
                'ins_val'                 => '130',
                'ins_no'                  => '21',
                'card_no'                 => '512',
                'cancel_date'             => '',
                'cancel_cause'            => 'because the time to finish tasks is to late because the time to finish tasks is to late',
                'sex'                     => 'male',
                'marital'                 => 'متزوج',
                'religion'                => 'مسلم',
                'military_service'        => 'معافى ',
                'tel'                     => '1111125214',
                'address'                 => '2st masr el gedida',
                'birth_date'              => '',
                'certificate'             => 'Bachelor',
                'cert_date'               => '',
                'cert_location'           =>'ain shams',
                'remark'                  => 'this is el rased project this is el rased project this is el rased project ',
                'user_id'                 => '123',
                'pic'                     =>'',
                'finger_id'               => '12',
                'd_hours'                  =>'7',
                'comm1'                   => '11',
                'comm2'                   =>'22'
            ),


        ));

    }
}