<?php
class hrLoansSeeder extends Seeder {
    public function run()
    {
        DB::table('hr_loans')->truncate();
        DB::table('hr_loans')->insert(array(
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
            array(
                'empCode'           => '221215',
                'loanDate'          => '',
                'loanVal'           => '12',
                'loanStart'         => '',
                'loanEnd'           => '',
                'userId'            => '123456',
                'loanCurrBal'       => '123',
                'finish'            => '1',
            ),
        ));
    }
}