<?php
class hrMonthChangesSeeder extends Seeder {
    public function run()
    {
        DB::table('hr_monthChanges')->truncate();
        DB::table('hr_monthChanges')->insert(array(
            array(
                'empCode'            => '221215',
                'transDate'          => '',
                'transSerial'        => '15',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'desDedCode'         => '545445',
                'dayCost'            => '100',
                'val'                => '1000.1',
                'cause'              =>'hard work hard work hard work',
                'userId'             => '123456',
                'canceled'           => '1',
                'cancelCause'        => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),
            array(
                'empCode'           => '221215',
                'transDate'          => '',
                'transSerial'      => '15',
                'forYear'       => '2015',
                'forMonth'       => '5',
                'desDedCode'      => '545445',
                'dayCost'       => '100',
                'val'           => '1000.1',
                'cause'          =>'hard work hard work hard work',
                'userId'            => '123456',
                'canceled'          => '1',
                'cancelCause'       => 'because the time to finish tasks is to late because the time to finish tasks is to late',
            ),

        ));

    }
}