<?php
class hrMSHeaderSeeder extends Seeder {
    public function run()
    {
        DB::table('hr_MSHeader')->truncate();
        DB::table('hr_MSHeader')->insert(array(
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
            array(
                'empCode'            => '221215',
                'forYear'            => '2015',
                'forMonth'           => '5',
                'fixedSalary'        => '1500.2',
                'deserves'           => '2000',
                'deductions'         => '238.15',
                'loan'               => '5000',
                'net'                => '3500',
                'gotSal'             => '1',
                'selDate'            => '',
                'userId'             => '123456',
            ),
        ));
    }
}
