<?php
class hrMSDetailsSeeder extends Seeder {
    public function run()
    {
        DB::table('hr_MSDetails')->truncate();
        DB::table('hr_MSDetails')->insert(array(
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
            array(
            'empCode'            => '221215',
            'forYear'            => '2015',
            'forMonth'           => '5',
            'desDedCode'         => '545445',
            'desDedType'         => 'el-rased',
            'desDedVal'          => '15000.2',
            ),
        ));
    }
}